FROM coreoasis/model_execution_worker

COPY ./model_data/ /var/oasis/model_data/
RUN touch /var/log/oasis/celery_worker.log
RUN chmod 666 /var/log/oasis/celery_worker.log

ENTRYPOINT ./utils/wait-for-it.sh "mysql:$MYSQL_PORT" -t 60 && \
    ./utils/wait-for-it.sh "rabbit:$RABBIT_PORT" -t 60 && \
    ./startup.sh && \
    tail -f /var/log/oasis/worker.log
