FROM coreoasis/model_execution_worker:OASIS_0_0_0_167

COPY ./model_execution_worker/ ./model_execution_worker/
COPY ./model_data/ /var/oasis/model_data/
RUN touch /var/log/oasis/celery_worker.log
RUN chmod 666 /var/log/oasis/celery_worker.log

ENTRYPOINT
# Define entry points here
